### ISSUE TITLE
Admin and sign in/up pages in Docker

### ISSUE THREAD

**Issue by immanuelfodor** [taroved/pol#34]
I feel this issue is not related to docker but at least I could try it out this way thanks to #32 

When I started up the project, I noticed that the menu is different from the online politepol.com. Namely, there are no Sign in/Sign up buttons and there is no admin page as well (https://politepol.com/en/admin/login/?next=/en/admin/). When I manually enter the URLs in the local env, Django outputs error pages which mean that debug mode is also enabled. 

How can one edit the added feeds in the local env without signin or admin pages? How could I make them work, do I miss a configuration somewhere that's also need to be added to the Dockerfile or start.sh?

**Comment by marlluslustosa** [comment]
The politepol tool is a great tool, perhaps the best on the market. Other competitors, such as fivefilters, do not have the same usability and ease of use, however, they are more robust, with recent updates and accept more entries and options.

With the management of the feeds the tool will get much better. I am trying, ardently, to help in designing the tool and updating it to new technologies, such as Docker.

So I ask the main developer @taroved @parallellium  if you couldn’t provide the feeds management interface, or else some way to enable it, if the error is mine.

Don't forget, a tool is built collaboratively. I have some customers who are already thinking about signing the official tool, because, as I said, it is very good in usability.

**Comment by taroved** [comment]
Sign Up and management of feeds will not be available in the near future
