### ISSUE TITLE
embedded iframe 404 errors

### ISSUE THREAD

**Issue by chasekidder** [taroved/pol#53]
Hi, I've been working on hosting politepol via docker on my server and have been able to get Django serving the appropriate pages. However, I am getting 404 errors in the embedded iframe when I attempt to setup a new feed. Here is a screenshot of the Django error: https://imgur.com/a/pcFMSRW . I think it might be due to something with nginx, but I don't know enough about it to be sure. I would appreciate any insight you could give me on this.

**Comment by taroved** [comment]
I'm not sure. But maybe you need to use port 8088

**Comment by sasagr** [comment]
@chasekidder @taroved 
I have the same issue also with port 8088. Any solution?

Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8088/downloader?url=https%3A%2F%2Fwww.newcoop.com%2Fsp-market-commentary%2F
Using the URLconf defined in frontend.urls, Django tried these URL patterns, in this order:

^en/
^setup_get_selected_ids$ [name='setup_get_selected_ids']
^setup_create_feed$ [name='setup_create_feed']
^setup_create_feed_ext$ [name='setup_create_feed_ext']
^setup_validate_selectors$ [name='setup_validate_selectors']
The current URL, downloader, didn't match any of these.

You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
